### ISSUE TITLE
i cant use luckperms

### ISSUE THREAD

**Issue by YutYutCraft** [AuraDevelopmentTeam/BungeeChat2#102]
What happens:

It says
[WARNING] Exception encountered when loading plugin: BungeeChat
java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
    at dev.aura.bungeechat.hook.LuckPermsHook.<init>(LuckPermsHook.java:18)
    at dev.aura.bungeechat.module.perms.LuckPermsModule.onEnable(LuckPermsModule.java:14)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
    at dev.aura.bungeechat.api.module.ModuleManager.enableModules(ModuleManager.java:33)
    at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:107)
    at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:69)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:226)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:308)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:39)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 11 more

When the server stops:
[SEVERE] Exception disabling plugin BungeeChat
java.lang.NullPointerException
    at net.md_5.bungee.event.EventBus.findHandlers(EventBus.java:64)
    at net.md_5.bungee.event.EventBus.unregister(EventBus.java:131)
    at net.md_5.bungee.api.plugin.PluginManager.unregisterListener(PluginManager.java:416)
    at dev.aura.bungeechat.module.ChatLoggingModule.onDisable(ChatLoggingModule.java:46)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
    at dev.aura.bungeechat.api.module.ModuleManager.disableModules(ModuleManager.java:37)
    at dev.aura.bungeechat.BungeeChat.onDisable(BungeeChat.java:124)
    at net.md_5.bungee.BungeeCord$4.run(BungeeCord.java:461)

some features from LuckPerms didn't work but on some restart it works and it back to not working again

Steps to reproduce:

1. I just start the server
2. and nothing works

Affected Versions:

- Minecraft: Aegis Bungeecord fork 7.0.2
- BungeeChat: 2.1.6
- LuckPerms: 5.0.100

**Comment by BrainStone** [comment]
https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility
