### ISSUE TITLE
Getting this error every time i put this in my bungeecord, Version of bungeecord im using is 1119

### ISSUE THREAD

**Issue by VyalLV** [AuraDevelopmentTeam/BungeeChat2#12]
00:03:21 [WARNING] Plugin performed restricted action, please inform them to use proper API methods: Illegal thread group access
java.security.AccessControlException: Plugin violation: Illegal thread group access
    at net.md_5.bungee.BungeeSecurityManager.checkRestricted(BungeeSecurityManager.java:39)
    at net.md_5.bungee.BungeeSecurityManager.checkAccess(BungeeSecurityManager.java:62)
    at java.lang.ThreadGroup.checkAccess(Unknown Source)
    at java.lang.Thread.init(Unknown Source)
    at java.lang.Thread.init(Unknown Source)
    at java.lang.Thread.<init>(Unknown Source)
    at java.util.TimerThread.<init>(Unknown Source)
    at java.util.Timer.<init>(Unknown Source)
    at java.util.Timer.<init>(Unknown Source)
    at dev.aura.bungeechat.shadow.org.bstats.Metrics.startSubmitting(Metrics.java:168)
    at dev.aura.bungeechat.shadow.org.bstats.Metrics.<init>(Metrics.java:102)
    at dev.aura.bungeechat.hook.metrics.MetricManager.sendMetrics(MetricManager.java:11)
    at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:111)
    at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:66)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:256)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by phit** [comment]
this is a bstats issue, you should report it to them

https://github.com/BtoBastian/bStats-Metrics/blob/master/bstats-bungeecord/src/main/java/org/bstats/Metrics.java#L246

for reference
https://github.com/SpigotMC/BungeeCord/commit/5d1b660

**Comment by shawn-ian** [comment]
Plugin is the result of the bStats developer using outdated/discouraged methods. (In this case using Timers instead of the BungeeCord scheduler). Already contacted the author of bStats, but like @phit said: paste the issue on the bStats GitHub. You might refer to this page: https://www.spigotmc.org/wiki/common-development-pitfalls-bungeecord/#creating-new-threads if so, since this is probably what is causing the error in this case. If the code of bStats is fixed, Bungee Chat will get updated within a short period of time.
