### ISSUE TITLE
2 antiswear options cause error

### ISSUE THREAD

**Issue by sassAsda** [AuraDevelopmentTeam/BungeeChat2#94]
#### Issue Description: 
enabling ignoreSpaces and/or ignoreDuplicateLetters in antiswear module causes errors

#### What happens:
error

#### What you expected to happen:
well i didnt expect it to throw an error

#### Steps to reproduce:

1. turn on ignorespaces in antiswear or ignoreDuplicateLetters (Same problem)
error pops up in console
...

____
#### Affected Versions: 

- Minecraft: im using 1.14.4
- BungeeChat:  2.1.6
- Other related plugins: 

#### Your most recent log or stack trace file where the issue was present: 

[10:12:56 WARN]: Exception encountered when loading plugin: BungeeChat
java.util.regex.PatternSyntaxException: Illegal hexadecimal escape sequence near index 19
(?<=^|\s)b\s*l\s*\x\s*{\s*0\s*0\s*F\s*6\s*}\s*d\s*m\s*a\s*n\s*n(?=\s|$)
                   ^
	at java.util.regex.Pattern.error(Unknown Source) ~[?:1.8.0_221]
	at java.util.regex.Pattern.x(Unknown Source) ~[?:1.8.0_221]
	at java.util.regex.Pattern.escape(Unknown Source) ~[?:1.8.0_221]
	at java.util.regex.Pattern.atom(Unknown Source) ~[?:1.8.0_221]
	at java.util.regex.Pattern.sequence(Unknown Source) ~[?:1.8.0_221]
	at java.util.regex.Pattern.expr(Unknown Source) ~[?:1.8.0_221]
	at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_221]
	at java.util.regex.Pattern.<init>(Unknown Source) ~[?:1.8.0_221]
	at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_221]
	at dev.aura.bungeechat.api.utils.RegexUtil.parseWildcardToPattern(RegexUtil.java:265) ~[?:?]
	at dev.aura.bungeechat.filter.SwearWordsFilter.lambda$new$0(SwearWordsFilter.java:20) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_221]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_221]
	at dev.aura.bungeechat.filter.SwearWordsFilter.<init>(SwearWordsFilter.java:22) ~[?:?]
	at dev.aura.bungeechat.module.AntiSwearModule.onEnable(AntiSwearModule.java:20) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_221]
	at dev.aura.bungeechat.api.module.ModuleManager.enableModules(ModuleManager.java:33) ~[?:?]
	at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:107) ~[?:?]
	at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:69) ~[?:?]

```
<!-- Or stack trace here (Remove this if you don't put anything here!) -->
```

**Comment by BrainStone** [comment]
This has been fixed in the dev version
