### ISSUE TITLE
Luckperms implementing error

### ISSUE THREAD

**Issue by GamingMineblox** [AuraDevelopmentTeam/BungeeChat2#96]
#### Issue Description:
When I start bungeecord it gives an error with trying to implement with luckperms
It also doesn't response to any commands like /staffchat 

#### What happens:
when I start bungeecord I get the following error from BungeeChat:
`14:50:08 [WARNING] Exception encountered when loading plugin: BungeeChat
java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
    at dev.aura.bungeechat.hook.LuckPermsHook.<init>(LuckPermsHook.java:18)
    at dev.aura.bungeechat.module.perms.LuckPermsModule.onEnable(LuckPermsModule.java:14)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
    at dev.aura.bungeechat.api.module.ModuleManager.enableModules(ModuleManager.java:33)
    at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:107)
    at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:69)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 11 more`

#### What you expected to happen:
Start the server without problems, showing the prefixes of Luckperms in the chat.

#### Steps to reproduce:

1. install luckperms to the bungeecord plugins
2. Install bungeechat to the bungeecord plugins
3. start the server on 1.14
...

____
#### Affected Versions:
2.1.6.855
- Minecraft: 1.14
- BungeeChat:  2.1.6.855
- Other related plugins: Luckperms

#### Your most recent log or stack trace file where the issue was present: 

`14:50:08 [WARNING] Exception encountered when loading plugin: BungeeChat
java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
    at dev.aura.bungeechat.hook.LuckPermsHook.<init>(LuckPermsHook.java:18)
    at dev.aura.bungeechat.module.perms.LuckPermsModule.onEnable(LuckPermsModule.java:14)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
    at dev.aura.bungeechat.api.module.ModuleManager.enableModules(ModuleManager.java:33)
    at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:107)
    at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:69)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 11 more`

**Comment by GamingMineblox** [comment]
i fixed it

**Comment by BrainStone** [comment]
Just as future reference for other people. This is how you solve it: https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility

**Comment by DmitryRendov** [comment]
@BrainStone @GamingMineblox -- how did you fix that, guys? I'm still having an expection on my bungee server with the following list of plugins:
* BungeeChat-2.1.7.1050-DEV.jar
* extension-default-assignments-1.0.0.jar
* extension-legacy-api-1.0.0.jar
* LuckPerms-Bungee-5.0.23.jar

`12:45:14 [WARNING] Exception encountered when loading plugin: BungeeChat
java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
    at dev.aura.bungeechat.hook.LuckPermsHook.<init>(LuckPermsHook.java:18)
    at dev.aura.bungeechat.module.perms.LuckPermsModule.onEnable(LuckPermsModule.java:14)
    at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at dev.aura.bungeechat.api.module.ModuleManager.enableModules(ModuleManager.java:45)
    at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:121)
    at dev.aura.bungeechat.BungeeChat.onEnable(BungeeChat.java:76)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 11 more
`

**Comment by DmitryRendov** [comment]
Sorry guys, I'm newb and placed to the wrong folder, *extension-legacy-api-1.0.0.jar* should be in `./plugins/LuckPerms/extensions`
Closed.
